### ISSUE TITLE
Wiki clarification

### ISSUE THREAD

**Issue by jducifuentes** [mv4wd/RCHourglass#1]
When you said in Wiki documentation  [:https://github.com/mv4wd/RCHourglass/wiki/DecoderBuild](https://github.com/mv4wd/RCHourglass/wiki/DecoderBuild) 

> Turn on the transponder and connect the scope to testpoints TP6 and TP8 in DC mode. The signal shoul be quite clear, less than 500mVpp for TP6 signal, centerend around 4 volts. TP8 shoul be about 3Vpp centered at about 1,8V.

Where are those Test points? Tp6 and TP8 ?

Thanks

edit: I got it! at decoder schematic. Will be useful to put a link to schematic in that wiki page.

**Comment by mv4wd** [comment]
Added link to the full schematic
