### ISSUE TITLE
Message and status in transponder

### ISSUE THREAD

**Issue by rmcarlsson** [mv4wd/RCHourglass#4]
Hi!

This of course not an issue, just a question. How is the message and status generated? I think I read something about a preamble.

  / Mikael

**Comment by mv4wd** [comment]
For old RC3 transponders, without the status, encoding schema was reversed, and the algorithm can be found in source file TransponderEncoding.cs, function encodeTransponderNoStatus. This modified version is to my knowledge giving the most correct results. For the status packets and RC4 encoding there's no such knowledge available as far as I know,

**Comment by henriquefchaves** [comment]
@rmcarlsson  could you complete the project?
