### ISSUE TITLE
help with the PIC programming please

### ISSUE THREAD

**Issue by xavieralexander** [mv4wd/RCHourglass#6]
Dear MV,
a lot of appreciation for your work on this project !
I am totaly new on PIC programming, i have the programming board and the PIC-chip of your diagram ( PIC16F18313 ) , and i want to program the PIC chip with PICkit 2 v2.61, but this chip is not in the supported chip list of the software, if i try a few other 16F models, it recognises the chip, although programming fails.
to be honest, i don't know what hex file is i need to import and write to the chip ... you have 8 different hex files in your github/rchourglass/firmware/transponder/bin   map.  I just copied the hole content of 1 hex file and pasted into a blanc .hex file for uploading to the programmer.
Your hourglass manager.exe deosn't detect anything in the third TAB ( PIC Programming )
any help to get me on the way would be greatly appreciate and if all works on my side, i will donate for sure for your work !
kind regards,
Xavier
![error-pickit](https://user-images.githubusercontent.com/20982120/159538208-c96ebdd5-e8c4-4688-b23b-c041cbc7c6a3.jpg)

**Comment by mv4wd** [comment]
PIC16F18313 can be programmed only with PicKit 3 or 4. Microchip does not support the latest PIC on older programmers.
The other way round is to use the decoder... but if you tinker with PICs, it's worth buying a PicKit3 o 4 even for debugging

**Comment by xavieralexander** [comment]
Thanks fot your answer, but i managed to add the PIC16f18313 manualy in the part family through the PicKitV2 .DAT file and it works just fine
![16f18313](https://user-images.githubusercontent.com/20982120/160249473-341f8372-d742-436c-94cd-7fd598e9a74c.jpg)

**Comment by mv4wd** [comment]
Great! The different hex are for different transponder numbers.
